/** @license React v16.2.0
 * react-dom-server.node.production.min.js
 *
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';var k=require("object-assign"),r=require("react"),aa=require("fbjs/lib/emptyFunction"),t=require("fbjs/lib/emptyObject"),ba=require("fbjs/lib/hyphenateStyleName"),ca=require("fbjs/lib/memoizeStringOnly"),da=require("stream");
function w(a){for(var b=arguments.length-1,g="Minified React error #"+a+"; visit http://facebook.github.io/react/docs/error-decoder.html?invariant\x3d"+a,f=0;f<b;f++)g+="\x26args[]\x3d"+encodeURIComponent(arguments[f+1]);b=Error(g+" for the full message or use the non-minified dev environment for full errors and additional helpful warnings.");b.name="Invariant Violation";b.framesToPop=1;throw b;}
var x={children:!0,dangerouslySetInnerHTML:!0,defaultValue:!0,defaultChecked:!0,innerHTML:!0,suppressContentEditableWarning:!0,suppressHydrationWarning:!0,style:!0};function z(a,b){return(a&b)===b}
var B={MUST_USE_PROPERTY:1,HAS_BOOLEAN_VALUE:4,HAS_NUMERIC_VALUE:8,HAS_POSITIVE_NUMERIC_VALUE:24,HAS_OVERLOADED_BOOLEAN_VALUE:32,HAS_STRING_BOOLEAN_VALUE:64,injectDOMPropertyConfig:function(a){var b=B,g=a.Properties||{},f=a.DOMAttributeNamespaces||{},h=a.DOMAttributeNames||{};a=a.DOMMutationMethods||{};for(var c in g){C.hasOwnProperty(c)?w("48",c):void 0;var d=c.toLowerCase(),e=g[c];d={attributeName:d,attributeNamespace:null,propertyName:c,mutationMethod:null,mustUseProperty:z(e,b.MUST_USE_PROPERTY),
hasBooleanValue:z(e,b.HAS_BOOLEAN_VALUE),hasNumericValue:z(e,b.HAS_NUMERIC_VALUE),hasPositiveNumericValue:z(e,b.HAS_POSITIVE_NUMERIC_VALUE),hasOverloadedBooleanValue:z(e,b.HAS_OVERLOADED_BOOLEAN_VALUE),hasStringBooleanValue:z(e,b.HAS_STRING_BOOLEAN_VALUE)};1>=d.hasBooleanValue+d.hasNumericValue+d.hasOverloadedBooleanValue?void 0:w("50",c);h.hasOwnProperty(c)&&(d.attributeName=h[c]);f.hasOwnProperty(c)&&(d.attributeNamespace=f[c]);a.hasOwnProperty(c)&&(d.mutationMethod=a[c]);C[c]=d}}},C={};
function ea(a,b){if(x.hasOwnProperty(a)||2<a.length&&("o"===a[0]||"O"===a[0])&&("n"===a[1]||"N"===a[1]))return!1;if(null===b)return!0;switch(typeof b){case "boolean":return D(a);case "undefined":case "number":case "string":case "object":return!0;default:return!1}}function E(a){return C.hasOwnProperty(a)?C[a]:null}
function D(a){if(x.hasOwnProperty(a))return!0;var b=E(a);if(b)return b.hasBooleanValue||b.hasStringBooleanValue||b.hasOverloadedBooleanValue;a=a.toLowerCase().slice(0,5);return"data-"===a||"aria-"===a}
var F=B,G=F.MUST_USE_PROPERTY,H=F.HAS_BOOLEAN_VALUE,I=F.HAS_NUMERIC_VALUE,J=F.HAS_POSITIVE_NUMERIC_VALUE,K=F.HAS_OVERLOADED_BOOLEAN_VALUE,L=F.HAS_STRING_BOOLEAN_VALUE,fa={Properties:{allowFullScreen:H,async:H,autoFocus:H,autoPlay:H,capture:K,checked:G|H,cols:J,contentEditable:L,controls:H,"default":H,defer:H,disabled:H,download:K,draggable:L,formNoValidate:H,hidden:H,loop:H,multiple:G|H,muted:G|H,noValidate:H,open:H,playsInline:H,readOnly:H,required:H,reversed:H,rows:J,rowSpan:I,scoped:H,seamless:H,
selected:G|H,size:J,start:I,span:J,spellCheck:L,style:0,tabIndex:0,itemScope:H,acceptCharset:0,className:0,htmlFor:0,httpEquiv:0,value:L},DOMAttributeNames:{acceptCharset:"accept-charset",className:"class",htmlFor:"for",httpEquiv:"http-equiv"},DOMMutationMethods:{value:function(a,b){if(null==b)return a.removeAttribute("value");"number"!==a.type||!1===a.hasAttribute("value")?a.setAttribute("value",""+b):a.validity&&!a.validity.badInput&&a.ownerDocument.activeElement!==a&&a.setAttribute("value",""+
b)}}},M=F.HAS_STRING_BOOLEAN_VALUE,N={xlink:"http://www.w3.org/1999/xlink",xml:"http://www.w3.org/XML/1998/namespace"},O={Properties:{autoReverse:M,externalResourcesRequired:M,preserveAlpha:M},DOMAttributeNames:{autoReverse:"autoReverse",externalResourcesRequired:"externalResourcesRequired",preserveAlpha:"preserveAlpha"},DOMAttributeNamespaces:{xlinkActuate:N.xlink,xlinkArcrole:N.xlink,xlinkHref:N.xlink,xlinkRole:N.xlink,xlinkShow:N.xlink,xlinkTitle:N.xlink,xlinkType:N.xlink,xmlBase:N.xml,xmlLang:N.xml,
xmlSpace:N.xml}},ha=/[\-\:]([a-z])/g;function ia(a){return a[1].toUpperCase()}
"accent-height alignment-baseline arabic-form baseline-shift cap-height clip-path clip-rule color-interpolation color-interpolation-filters color-profile color-rendering dominant-baseline enable-background fill-opacity fill-rule flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight glyph-name glyph-orientation-horizontal glyph-orientation-vertical horiz-adv-x horiz-origin-x image-rendering letter-spacing lighting-color marker-end marker-mid marker-start overline-position overline-thickness paint-order panose-1 pointer-events rendering-intent shape-rendering stop-color stop-opacity strikethrough-position strikethrough-thickness stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke-width text-anchor text-decoration text-rendering underline-position underline-thickness unicode-bidi unicode-range units-per-em v-alphabetic v-hanging v-ideographic v-mathematical vector-effect vert-adv-y vert-origin-x vert-origin-y word-spacing writing-mode x-height xlink:actuate xlink:arcrole xlink:href xlink:role xlink:show xlink:title xlink:type xml:base xmlns:xlink xml:lang xml:space".split(" ").forEach(function(a){var b=a.replace(ha,
ia);O.Properties[b]=0;O.DOMAttributeNames[b]=a});F.injectDOMPropertyConfig(fa);F.injectDOMPropertyConfig(O);var P="function"===typeof Symbol&&Symbol["for"]?Symbol["for"]("react.fragment"):60107,ja=/["'&<>]/;
function Q(a){if("boolean"===typeof a||"number"===typeof a)return""+a;a=""+a;var b=ja.exec(a);if(b){var g="",f,h=0;for(f=b.index;f<a.length;f++){switch(a.charCodeAt(f)){case 34:b="\x26quot;";break;case 38:b="\x26amp;";break;case 39:b="\x26#x27;";break;case 60:b="\x26lt;";break;case 62:b="\x26gt;";break;default:continue}h!==f&&(g+=a.substring(h,f));h=f+1;g+=b}a=h!==f?g+a.substring(h,f):g}return a}
var ka=/^[:A-Z_a-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD][:A-Z_a-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\-.0-9\u00B7\u0300-\u036F\u203F-\u2040]*$/,R={},S={};function la(a){if(S.hasOwnProperty(a))return!0;if(R.hasOwnProperty(a))return!1;if(ka.test(a))return S[a]=!0;R[a]=!0;return!1}
function ma(a,b){var g=E(a);if(g){if(null==b||g.hasBooleanValue&&!b||g.hasNumericValue&&isNaN(b)||g.hasPositiveNumericValue&&1>b||g.hasOverloadedBooleanValue&&!1===b)return"";var f=g.attributeName;if(g.hasBooleanValue||g.hasOverloadedBooleanValue&&!0===b)return f+'\x3d""';if("boolean"!==typeof b||D(a))return f+"\x3d"+('"'+Q(b)+'"')}else if(ea(a,b))return null==b?"":a+"\x3d"+('"'+Q(b)+'"');return null}var T={html:"http://www.w3.org/1999/xhtml",mathml:"http://www.w3.org/1998/Math/MathML",svg:"http://www.w3.org/2000/svg"};
function U(a){switch(a){case "svg":return"http://www.w3.org/2000/svg";case "math":return"http://www.w3.org/1998/Math/MathML";default:return"http://www.w3.org/1999/xhtml"}}
var V={area:!0,base:!0,br:!0,col:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0},na=k({menuitem:!0},V),W={animationIterationCount:!0,borderImageOutset:!0,borderImageSlice:!0,borderImageWidth:!0,boxFlex:!0,boxFlexGroup:!0,boxOrdinalGroup:!0,columnCount:!0,columns:!0,flex:!0,flexGrow:!0,flexPositive:!0,flexShrink:!0,flexNegative:!0,flexOrder:!0,gridRow:!0,gridRowEnd:!0,gridRowSpan:!0,gridRowStart:!0,gridColumn:!0,gridColumnEnd:!0,gridColumnSpan:!0,gridColumnStart:!0,
fontWeight:!0,lineClamp:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,tabSize:!0,widows:!0,zIndex:!0,zoom:!0,fillOpacity:!0,floodOpacity:!0,stopOpacity:!0,strokeDasharray:!0,strokeDashoffset:!0,strokeMiterlimit:!0,strokeOpacity:!0,strokeWidth:!0},oa=["Webkit","ms","Moz","O"];Object.keys(W).forEach(function(a){oa.forEach(function(b){b=b+a.charAt(0).toUpperCase()+a.substring(1);W[b]=W[a]})});var X=r.Children.toArray,pa=aa.thatReturns(""),qa={listing:!0,pre:!0,textarea:!0};
function ra(a){return"string"===typeof a?a:"function"===typeof a?a.displayName||a.name:null}var sa=/^[a-zA-Z][a-zA-Z:_\.\-\d]*$/,ta={},ua=ca(function(a){return ba(a)});function va(a){var b="";r.Children.forEach(a,function(a){null==a||"string"!==typeof a&&"number"!==typeof a||(b+=a)});return b}function wa(a,b){if(a=a.contextTypes){var g={},f;for(f in a)g[f]=b[f];b=g}else b=t;return b}var xa={children:null,dangerouslySetInnerHTML:null,suppressContentEditableWarning:null,suppressHydrationWarning:null};
function ya(a,b){void 0===a&&w("152",ra(b)||"Component")}
function za(a,b){for(;r.isValidElement(a);){var g=a,f=g.type;if("function"!==typeof f)break;a=wa(f,b);var h=[],c=!1,d={isMounted:function(){return!1},enqueueForceUpdate:function(){if(null===h)return null},enqueueReplaceState:function(b,a){c=!0;h=[a]},enqueueSetState:function(b,a){if(null===h)return null;h.push(a)}};if(f.prototype&&f.prototype.isReactComponent)var e=new f(g.props,a,d);else if(e=f(g.props,a,d),null==e||null==e.render){a=e;ya(a,f);continue}e.props=g.props;e.context=a;e.updater=d;d=e.state;
void 0===d&&(e.state=d=null);if(e.componentWillMount)if(e.componentWillMount(),h.length){d=h;var m=c;h=null;c=!1;if(m&&1===d.length)e.state=d[0];else{var p=m?d[0]:e.state,l=!0;for(m=m?1:0;m<d.length;m++){var n=d[m];if(n="function"===typeof n?n.call(e,p,g.props,a):n)l?(l=!1,p=k({},p,n)):k(p,n)}e.state=p}}else h=null;a=e.render();ya(a,f);if("function"===typeof e.getChildContext&&(g=f.childContextTypes,"object"===typeof g)){var A=e.getChildContext();for(var y in A)y in g?void 0:w("108",ra(f)||"Unknown",
y)}A&&(b=k({},b,A))}return{child:a,context:b}}
var Y=function(){function a(b,g){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");r.isValidElement(b)?b.type!==P?b=[b]:(b=b.props.children,b=r.isValidElement(b)?[b]:X(b)):b=X(b);this.stack=[{domNamespace:T.html,children:b,childIndex:0,context:t,footer:""}];this.exhausted=!1;this.currentSelectValue=null;this.previousWasTextNode=!1;this.makeStaticMarkup=g}a.prototype.read=function(a,g){var b={};if(this.exhausted)return null;for(var h="";h.length<a;){if(0===this.stack.length){this.exhausted=
!0;break}var c=this.stack[this.stack.length-1];if(c.childIndex>=c.children.length){var d=c.footer;h+=d;""!==d&&(this.previousWasTextNode=!1);this.stack.pop();"select"===c.tag&&(this.currentSelectValue=null)}else d=c.children[c.childIndex++],d.props.cacheKey?g.storage.get(d.props.cacheKey)?h+=g.storage.get(d.props.cacheKey):(b[d.props.cacheKey]=h.length,h+=this.render(d,c.context,c.domNamespace)):h+=this.render(d,c.context,c.domNamespace)}for(var e in b){a=[];d=h.indexOf("\x3e",b[e])+1;var m=h.slice(b[e],
d);c=d;if("/"!==h[d-2])for(m.slice(1),a.push(m);0!==a.length;)c=h.indexOf("\x3c",c),d=h.indexOf("\x3e",c)+1,"/"!==h[d-2]&&("/"!==h[c+1]?(c=h.slice(c,d),c.slice(1),a.push(c)):a.pop()),c=d;g.storage.set(e,h.slice(b[e],c))}return h};a.prototype.render=function(a,g,f){if("string"===typeof a||"number"===typeof a){f=""+a;if(""===f)return"";if(this.makeStaticMarkup)return Q(f);if(this.previousWasTextNode)return"\x3c!-- --\x3e"+Q(f);this.previousWasTextNode=!0;return Q(f)}g=za(a,g);a=g.child;g=g.context;
if(null===a||!1===a)return"";if(r.isValidElement(a))return a.type===P?(a=X(a.props.children),this.stack.push({domNamespace:f,children:a,childIndex:0,context:g,footer:""}),""):this.renderDOM(a,g,f);a=X(a);this.stack.push({domNamespace:f,children:a,childIndex:0,context:g,footer:""});return""};a.prototype.renderDOM=function(a,g,f){var b=a.type.toLowerCase();f===T.html&&U(b);ta.hasOwnProperty(b)||(sa.test(b)?void 0:w("65",b),ta[b]=!0);var c=a.props;if("input"===b)c=k({type:void 0},c,{defaultChecked:void 0,
defaultValue:void 0,value:null!=c.value?c.value:c.defaultValue,checked:null!=c.checked?c.checked:c.defaultChecked});else if("textarea"===b){var d=c.value;if(null==d){d=c.defaultValue;var e=c.children;null!=e&&(null!=d?w("92"):void 0,Array.isArray(e)&&(1>=e.length?void 0:w("93"),e=e[0]),d=""+e);null==d&&(d="")}c=k({},c,{value:void 0,children:""+d})}else if("select"===b)this.currentSelectValue=null!=c.value?c.value:c.defaultValue,c=k({},c,{value:void 0});else if("option"===b){e=this.currentSelectValue;
var m=va(c.children);if(null!=e){var p=null!=c.value?c.value+"":m;d=!1;if(Array.isArray(e))for(var l=0;l<e.length;l++){if(""+e[l]===p){d=!0;break}}else d=""+e===p;c=k({selected:void 0,children:void 0},c,{selected:d,children:m})}}if(d=c)na[b]&&(null!=d.children||null!=d.dangerouslySetInnerHTML?w("137",b,pa()):void 0),null!=d.dangerouslySetInnerHTML&&(null!=d.children?w("60"):void 0,"object"===typeof d.dangerouslySetInnerHTML&&"__html"in d.dangerouslySetInnerHTML?void 0:w("61")),null!=d.style&&"object"!==
typeof d.style?w("62",pa()):void 0;d=c;e=this.makeStaticMarkup;m=1===this.stack.length;p="\x3c"+a.type;for(q in d)if(d.hasOwnProperty(q)){var n=d[q];if(null!=n){if("style"===q){l=void 0;var A="",y="";for(l in n)if(n.hasOwnProperty(l)){var u=0===l.indexOf("--"),v=n[l];null!=v&&(A+=y+ua(l)+":",y=l,u=null==v||"boolean"===typeof v||""===v?"":u||"number"!==typeof v||0===v||W.hasOwnProperty(y)&&W[y]?(""+v).trim():v+"px",A+=u,y=";")}n=A||null}l=null;b:if(u=b,v=d,-1===u.indexOf("-"))u="string"===typeof v.is;
else switch(u){case "annotation-xml":case "color-profile":case "font-face":case "font-face-src":case "font-face-uri":case "font-face-format":case "font-face-name":case "missing-glyph":u=!1;break b;default:u=!0}u?xa.hasOwnProperty(q)||(l=q,l=la(l)&&null!=n?l+"\x3d"+('"'+Q(n)+'"'):""):l=ma(q,n);l&&(p+=" "+l)}}e||m&&(p+=' data-reactroot\x3d""');var q=p;d="";V.hasOwnProperty(b)?q+="/\x3e":(q+="\x3e",d="\x3c/"+a.type+"\x3e");a:{e=c.dangerouslySetInnerHTML;if(null!=e){if(null!=e.__html){e=e.__html;break a}}else if(e=
c.children,"string"===typeof e||"number"===typeof e){e=Q(e);break a}e=null}null!=e?(c=[],qa[b]&&"\n"===e.charAt(0)&&(q+="\n"),q+=e):c=X(c.children);a=a.type;f=null==f||"http://www.w3.org/1999/xhtml"===f?U(a):"http://www.w3.org/2000/svg"===f&&"foreignObject"===a?"http://www.w3.org/1999/xhtml":f;this.stack.push({domNamespace:f,tag:b,children:c,childIndex:0,context:g,footer:d});this.previousWasTextNode=!1;return q};return a}();
function Aa(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}
var Ba=function(a){function b(g,f){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var h=a.call(this,{});if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");h=!h||"object"!==typeof h&&"function"!==typeof h?this:h;h.partialRenderer=new Y(g,f);return h}Aa(b,a);b.prototype._read=function(a){try{this.push(this.partialRenderer.read(a))}catch(f){this.emit("error",f)}};return b}(da.Readable),Ca={renderToString:function(a,b){return(new Y(a,
!1)).read(Infinity,b)},renderToStaticMarkup:function(a){return(new Y(a,!0)).read(Infinity)},renderToNodeStream:function(a){return new Ba(a,!1)},renderToStaticNodeStream:function(a){return new Ba(a,!0)},version:"16.2.0"},Da=Object.freeze({default:Ca}),Z=Da&&Ca||Da;module.exports=Z["default"]?Z["default"]:Z;
